/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'UpdateTodo': ApiRouteHandler<{ title?: string | unknown; description?: string | unknown; completed?: boolean | unknown }, ApiResponse<200, { id?: string; title?: string; description?: string; completed?: boolean; createdAt?: string; updatedAt?: string }> | ApiResponse<400, { error?: string }> | ApiResponse<404, { error?: string }>, never>
    'GetTodo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id?: string; title?: string; description?: string; completed?: boolean; createdAt?: string; updatedAt?: string }> | ApiResponse<404, { error?: string }>, never>
    'GetTodos': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { todos?: Array<{ id?: string; title?: string; description?: string; completed?: boolean; createdAt?: string; updatedAt?: string }>; count?: number }>, never>
    'DeleteTodo': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message?: string; id?: string }> | ApiResponse<404, { error?: string }>, never>
    'CreateTodo': ApiRouteHandler<{ title: string; description?: string; completed?: boolean }, ApiResponse<201, { id: string; title: string; description: string; completed: boolean; createdAt: string; updatedAt: string }> | ApiResponse<400, { error: string }>, never>
    'ListJobs': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { jobs?: Array<{ job_id?: string; role?: string; status?: string; created_at?: string; updated_at?: string }>; count?: unknown; summary?: { pending?: unknown; processing?: unknown; completed?: unknown; failed?: unknown } }>, never>
    'GetJob': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { job_id?: string; role?: string; description?: string; yoe?: unknown; comp?: string; status?: string; created_at?: string; updated_at?: string; file_path?: string; content?: string; error?: string }> | ApiResponse<404, { error?: string }>, never>
    'GenerateJobDescription': EventHandler<{ job_id: string; role: string; description: string; yoe: unknown; comp?: string | unknown }, never>
    'CreateJob': ApiRouteHandler<{ role: string; description: string; yoe: unknown; comp?: string | unknown }, ApiResponse<201, { job_id: string; role: string; description: string; yoe: unknown; comp: string | unknown; status: string; message: string; created_at: string }> | ApiResponse<400, { error: string; details?: Record<string, unknown> | unknown }>, { topic: 'generate-job-description'; data: { job_id: string; role: string; description: string; yoe: unknown; comp?: string | unknown } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'PostGreeting': ApiRouteHandler<{ name: string }, ApiResponse<200, { greeting: string; message: string }>, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}